export const ProductData = [
  {
    id: 0,
    name: 'Almond Toe Court Shoes, Patent Black',
    category: 'Women’s Footwear',
    price: 99.00,
    quantity: 5,
    image: 'http://www.wearthemwithlove.co.uk/image/cache/data/category_20/lisa-almond-toe-mid-heel-court-black-patent-women-heels-womens-shoes-ntnayfwiy-161-500x500.jpg',
  },
  {
    id: 1,
    name: 'Suede Shoes, Blue',
    category: 'Women’s Footwear',
    price: 42.00,
    quantity: 4,
    image: 'https://www.michelshoes.com/180-thickbox_default/monk-blue-suede-shoes-elijah-.jpg',
  },
  {
    id: 2,
    name: 'Leather Driver Saddle Loafers, Tan',
    category: 'Men’s Footwear',
    price: 34.00,
    quantity: 12,
    image: 'https://www.shoecarnival.com/dw/image/v2/BBSZ_PRD/on/demandware.static/-/Sites-scvl-master-catalog/default/dwffde5ead/90484_173525_1.jpg?sw=700&sh=593&sm=fit',
  },
  {
    id: 3,
    name: 'Flip Flops, Red',
    category: 'Men’s Footwear',
    price: 19.00,
    quantity: 6,
    image: 'https://s1.thcdn.com/productimg/0/600/600/58/10301758-1357811154-763561.jpg',
  },
  {
    id: 4,
    name: 'Flip Flops, Blue',
    category: 'Men’s Footwear',
    price: 19.00,
    quantity: 0,
    image: 'https://www.dollartree.com/assets/product_images_2016/styles/xlarge/237525.jpg',
  },
  {
    id: 5,
    name: 'Gold Button Cardigan, Black',
    category: 'Women’s Casualwear',
    price: 167.00,
    quantity: 6,
    image: 'https://di2ponv0v5otw.cloudfront.net/posts/2018/04/19/5ad8e44536b9de2264972ea8/m_5ad8e47c8290afafa5fa2f3c.jpg',
  },
  {
    id: 6,
    name: 'Cotton Shorts, Medium Red',
    category: 'Women’s Casualwear',
    price: 30.00,
    quantity: 5,
    image: 'https://ae01.alicdn.com/kf/HTB1PD8RMFXXXXblXVXXq6xXFXXXb/Plus-Size-Cotton-Loose-Women-Shorts-2016-Summer-Fashion-Women-Short-Feminino-Casual-Shorts-Female-Clothing.jpg_640x640.jpg',
  },
  {
    id: 7,
    name: 'Fine Stripe Short Sleeve Shirt, Grey',
    category: 'Men’s Casualwear',
    price: 49.99,
    quantity: 9,
    image: 'https://images-na.ssl-images-amazon.com/images/I/81DYb-DmVxL._SX385_.jpg',
  },
  {
    id: 8,
    name: 'Fine Stripe Short Sleeve Shirt, Green',
    category: 'Men’s Casualwear',
    price: 39.99,
    quantity: 3,
    image: 'https://img.looksgud.com/upload/item-image/910/jihs/jihs-gap-men-s-short-sleeve-all-over-fine-stripe-pique-polo_500x500_4.jpg',
  },
  {
    id: 9,
    name: 'Sharkskin Waistcoat, Charcoal',
    category: 'Men’s Casualwear',
    price: 75.00,
    quantity: 2,
    image: 'https://ae01.alicdn.com/kf/HTB1tkfVLpXXXXXuXXXXq6xXFXXXT/Spring-Autumn-hot-sale-Men-Vest-Brand-Casual-wear-Simple-Business-slim-vest-Metal-chain-waistcoat.jpg',
  },
  {
    id: 10,
    name: 'Lightweight Patch Pocket Blazer, Deer',
    category: 'Men’s Formalwear',
    price: 175.50,
    quantity: 1,
    image: 'https://resizer.goxip.com/600,q75,fit/https://cdn.goxip.com/aff_images/post-overalls-lined-deer-hunter-jacket-11542015.jpg',
  },
  {
    id: 11,
    name: 'Bird Print Dress, Black',
    category: 'Women’s Formalwear',
    price: 270.00,
    quantity: 10,
    image: 'https://ae01.alicdn.com/kf/HTB1KFhOeBcHL1JjSZFBq6yiGXXaM/SHEIN-Crane-Bird-Print-Swing-Dress-Black-Three-Quarter-Length-Sleeve-Casual-A-Line-Dress-Elegant.jpg_640x640.jpg',
  },
  {
    id: 12,
    name: 'Mid Twist Cut-Out Dress, Pink',
    category: 'Women’s Formalwear',
    price: 540.00,
    quantity: 5,
    image: 'http://media2.newlookassets.com/i/newlook/581790470.jpg',
  }
];

export default ProductData;