<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Scroll Window Height</title>
	<link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>

	<section class="fsWindow" id="window1">
		<h1>Window 1</h1>
		<h3>jQuery window height sets the div height</h3>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lacus nisl, eleifend in ipsum in, posuere placerat nisi. In hendrerit augue vitae nisi accumsan, sed mattis enim porta. Sed dignissim tempus ex, vitae dignissim magna consequat vel. Praesent non ex ipsum. Etiam lacinia eget odio consequat accumsan. Fusce quis lectus mi. Donec condimentum lacinia leo a imperdiet. Suspendisse aliquam ipsum at tincidunt gravida. Donec gravida aliquam sapien malesuada fermentum. Maecenas tellus purus, tempor ac ante sit amet, lobortis fermentum libero. In vitae dignissim odio, ac molestie nibh. Proin auctor et nibh consequat tristique. Aenean ac purus ac erat suscipit commodo sed dictum eros. Aliquam nec dignissim justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>
		<p>Proin vel est ultrices, tincidunt neque quis, efficitur massa. Aenean lobortis enim non elit auctor pretium. Mauris vestibulum pellentesque porttitor. Duis vestibulum sed nulla sit amet volutpat. Sed vel sem id arcu sollicitudin efficitur. Aenean tincidunt odio rhoncus libero ultrices, feugiat porta metus laoreet. Donec sit amet condimentum arcu. Nunc vel iaculis augue, sed auctor sem. Nam vel malesuada diam, quis semper lorem. Phasellus vitae enim metus. Suspendisse imperdiet felis est. Nam mi quam, venenatis non sem eget, convallis tincidunt quam.</p>
		<p>Aliquam porttitor turpis nec quam aliquet interdum. Curabitur et purus rutrum, euismod tellus et, tempus purus. Quisque dolor nunc, hendrerit a velit nec, vehicula blandit ipsum. Vivamus ut nibh eu justo hendrerit fermentum ut quis elit. Phasellus quis mi id quam suscipit cursus. Nulla felis nibh, pellentesque nec felis sed, interdum sagittis ipsum. Vivamus nec varius magna. Sed id felis blandit, ultricies leo in, venenatis justo. Pellentesque congue malesuada volutpat. Duis porta id elit ut molestie. Quisque consequat quam congue, suscipit orci at, tempor leo. In imperdiet, sapien et varius lacinia, eros leo malesuada turpis, at fermentum purus eros ultrices massa. Cras mi elit, mollis vitae lobortis vitae, condimentum non quam. Etiam at mauris vel erat volutpat auctor.</p>
		<p>Integer eu massa a tortor ullamcorper dignissim facilisis in diam. Nulla vel dolor molestie velit dapibus condimentum. Donec risus elit, tempor nec lacus in, tempus porttitor lectus. Nam felis dui, feugiat non tempus eget, iaculis nec lacus. Praesent non justo eget diam imperdiet dignissim. Vestibulum finibus nisl et arcu tristique finibus. Phasellus imperdiet turpis sed metus scelerisque, consectetur commodo libero pharetra. In hac habitasse platea dictumst. Vestibulum hendrerit pellentesque purus, ullamcorper molestie lacus posuere sollicitudin.</p>
	</section>

	<section class="fsWindow" id="window2">
		<h1>Window 2</h1>
		<h3>Using jQuery Mobile 'scrollstop' you can find when scrolling has stopped</h3>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lacus nisl, eleifend in ipsum in, posuere placerat nisi. In hendrerit augue vitae nisi accumsan, sed mattis enim porta. Sed dignissim tempus ex, vitae dignissim magna consequat vel. Praesent non ex ipsum. Etiam lacinia eget odio consequat accumsan. Fusce quis lectus mi. Donec condimentum lacinia leo a imperdiet. Suspendisse aliquam ipsum at tincidunt gravida. Donec gravida aliquam sapien malesuada fermentum. Maecenas tellus purus, tempor ac ante sit amet, lobortis fermentum libero. In vitae dignissim odio, ac molestie nibh. Proin auctor et nibh consequat tristique. Aenean ac purus ac erat suscipit commodo sed dictum eros. Aliquam nec dignissim justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>
		<p>Proin vel est ultrices, tincidunt neque quis, efficitur massa. Aenean lobortis enim non elit auctor pretium. Mauris vestibulum pellentesque porttitor. Duis vestibulum sed nulla sit amet volutpat. Sed vel sem id arcu sollicitudin efficitur. Aenean tincidunt odio rhoncus libero ultrices, feugiat porta metus laoreet. Donec sit amet condimentum arcu. Nunc vel iaculis augue, sed auctor sem. Nam vel malesuada diam, quis semper lorem. Phasellus vitae enim metus. Suspendisse imperdiet felis est. Nam mi quam, venenatis non sem eget, convallis tincidunt quam.</p>
		<p>Aliquam porttitor turpis nec quam aliquet interdum. Curabitur et purus rutrum, euismod tellus et, tempus purus. Quisque dolor nunc, hendrerit a velit nec, vehicula blandit ipsum. Vivamus ut nibh eu justo hendrerit fermentum ut quis elit. Phasellus quis mi id quam suscipit cursus. Nulla felis nibh, pellentesque nec felis sed, interdum sagittis ipsum. Vivamus nec varius magna. Sed id felis blandit, ultricies leo in, venenatis justo. Pellentesque congue malesuada volutpat. Duis porta id elit ut molestie. Quisque consequat quam congue, suscipit orci at, tempor leo. In imperdiet, sapien et varius lacinia, eros leo malesuada turpis, at fermentum purus eros ultrices massa. Cras mi elit, mollis vitae lobortis vitae, condimentum non quam. Etiam at mauris vel erat volutpat auctor.</p>
		<p>Integer eu massa a tortor ullamcorper dignissim facilisis in diam. Nulla vel dolor molestie velit dapibus condimentum. Donec risus elit, tempor nec lacus in, tempus porttitor lectus. Nam felis dui, feugiat non tempus eget, iaculis nec lacus. Praesent non justo eget diam imperdiet dignissim. Vestibulum finibus nisl et arcu tristique finibus. Phasellus imperdiet turpis sed metus scelerisque, consectetur commodo libero pharetra. In hac habitasse platea dictumst. Vestibulum hendrerit pellentesque purus, ullamcorper molestie lacus posuere sollicitudin.</p>
	</section>

	<section class="fsWindow" id="window3">
		<h1>Window 3</h1>
		<h3>If it stops with more than 50% in the screen will scroll to the page</h3>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lacus nisl, eleifend in ipsum in, posuere placerat nisi. In hendrerit augue vitae nisi accumsan, sed mattis enim porta. Sed dignissim tempus ex, vitae dignissim magna consequat vel. Praesent non ex ipsum. Etiam lacinia eget odio consequat accumsan. Fusce quis lectus mi. Donec condimentum lacinia leo a imperdiet. Suspendisse aliquam ipsum at tincidunt gravida. Donec gravida aliquam sapien malesuada fermentum. Maecenas tellus purus, tempor ac ante sit amet, lobortis fermentum libero. In vitae dignissim odio, ac molestie nibh. Proin auctor et nibh consequat tristique. Aenean ac purus ac erat suscipit commodo sed dictum eros. Aliquam nec dignissim justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>
		<p>Proin vel est ultrices, tincidunt neque quis, efficitur massa. Aenean lobortis enim non elit auctor pretium. Mauris vestibulum pellentesque porttitor. Duis vestibulum sed nulla sit amet volutpat. Sed vel sem id arcu sollicitudin efficitur. Aenean tincidunt odio rhoncus libero ultrices, feugiat porta metus laoreet. Donec sit amet condimentum arcu. Nunc vel iaculis augue, sed auctor sem. Nam vel malesuada diam, quis semper lorem. Phasellus vitae enim metus. Suspendisse imperdiet felis est. Nam mi quam, venenatis non sem eget, convallis tincidunt quam.</p>
		<p>Aliquam porttitor turpis nec quam aliquet interdum. Curabitur et purus rutrum, euismod tellus et, tempus purus. Quisque dolor nunc, hendrerit a velit nec, vehicula blandit ipsum. Vivamus ut nibh eu justo hendrerit fermentum ut quis elit. Phasellus quis mi id quam suscipit cursus. Nulla felis nibh, pellentesque nec felis sed, interdum sagittis ipsum. Vivamus nec varius magna. Sed id felis blandit, ultricies leo in, venenatis justo. Pellentesque congue malesuada volutpat. Duis porta id elit ut molestie. Quisque consequat quam congue, suscipit orci at, tempor leo. In imperdiet, sapien et varius lacinia, eros leo malesuada turpis, at fermentum purus eros ultrices massa. Cras mi elit, mollis vitae lobortis vitae, condimentum non quam. Etiam at mauris vel erat volutpat auctor.</p>
		<p>Integer eu massa a tortor ullamcorper dignissim facilisis in diam. Nulla vel dolor molestie velit dapibus condimentum. Donec risus elit, tempor nec lacus in, tempus porttitor lectus. Nam felis dui, feugiat non tempus eget, iaculis nec lacus. Praesent non justo eget diam imperdiet dignissim. Vestibulum finibus nisl et arcu tristique finibus. Phasellus imperdiet turpis sed metus scelerisque, consectetur commodo libero pharetra. In hac habitasse platea dictumst. Vestibulum hendrerit pellentesque purus, ullamcorper molestie lacus posuere sollicitudin.</p>
	</section>

	<section class="fsWindow" id="window4">
		<h1>Window 4</h1>
		<h3>Voila</h3>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lacus nisl, eleifend in ipsum in, posuere placerat nisi. In hendrerit augue vitae nisi accumsan, sed mattis enim porta. Sed dignissim tempus ex, vitae dignissim magna consequat vel. Praesent non ex ipsum. Etiam lacinia eget odio consequat accumsan. Fusce quis lectus mi. Donec condimentum lacinia leo a imperdiet. Suspendisse aliquam ipsum at tincidunt gravida. Donec gravida aliquam sapien malesuada fermentum. Maecenas tellus purus, tempor ac ante sit amet, lobortis fermentum libero. In vitae dignissim odio, ac molestie nibh. Proin auctor et nibh consequat tristique. Aenean ac purus ac erat suscipit commodo sed dictum eros. Aliquam nec dignissim justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>
		<p>Proin vel est ultrices, tincidunt neque quis, efficitur massa. Aenean lobortis enim non elit auctor pretium. Mauris vestibulum pellentesque porttitor. Duis vestibulum sed nulla sit amet volutpat. Sed vel sem id arcu sollicitudin efficitur. Aenean tincidunt odio rhoncus libero ultrices, feugiat porta metus laoreet. Donec sit amet condimentum arcu. Nunc vel iaculis augue, sed auctor sem. Nam vel malesuada diam, quis semper lorem. Phasellus vitae enim metus. Suspendisse imperdiet felis est. Nam mi quam, venenatis non sem eget, convallis tincidunt quam.</p>
		<p>Aliquam porttitor turpis nec quam aliquet interdum. Curabitur et purus rutrum, euismod tellus et, tempus purus. Quisque dolor nunc, hendrerit a velit nec, vehicula blandit ipsum. Vivamus ut nibh eu justo hendrerit fermentum ut quis elit. Phasellus quis mi id quam suscipit cursus. Nulla felis nibh, pellentesque nec felis sed, interdum sagittis ipsum. Vivamus nec varius magna. Sed id felis blandit, ultricies leo in, venenatis justo. Pellentesque congue malesuada volutpat. Duis porta id elit ut molestie. Quisque consequat quam congue, suscipit orci at, tempor leo. In imperdiet, sapien et varius lacinia, eros leo malesuada turpis, at fermentum purus eros ultrices massa. Cras mi elit, mollis vitae lobortis vitae, condimentum non quam. Etiam at mauris vel erat volutpat auctor.</p>
		<p>Integer eu massa a tortor ullamcorper dignissim facilisis in diam. Nulla vel dolor molestie velit dapibus condimentum. Donec risus elit, tempor nec lacus in, tempus porttitor lectus. Nam felis dui, feugiat non tempus eget, iaculis nec lacus. Praesent non justo eget diam imperdiet dignissim. Vestibulum finibus nisl et arcu tristique finibus. Phasellus imperdiet turpis sed metus scelerisque, consectetur commodo libero pharetra. In hac habitasse platea dictumst. Vestibulum hendrerit pellentesque purus, ullamcorper molestie lacus posuere sollicitudin.</p>
	</section>

<script type="text/javascript" src="js/jquery.js"></script>
<script src="http://code.jquery.com/mobile/1.4.2/jquery.mobile-1.4.2.min.js"></script>
<script type="text/javascript" src="js/init.js"></script>

</body>
</html>